# Generated by Django 5.0.1 on 2024-01-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_customer_customersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['headline']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='myFirstApp.publications'),
        ),
    ]
